sudo: false
language: node_js
node_js:
  - "4"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
 - cd 4_integration
script:
  - npm install
  - npm run start-backend || exit 0
  - npm test
