sudo: false
language: node_js
node_js:
  - "4"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - cd 4_integration && npm install && npm run start-backend | ./node_modules/.bin/karma start --single-run --browsers PhantomJS
